@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%\..\..\..") do set "REPO_ROOT=%%~fI"
if "%LOCALAPPDATA%"=="" (
  set "BRIDGE_LOG_DIR=%TEMP%\BYOM\bridge\logs"
  set "BRIDGE_STATE_DIR=%TEMP%\BYOM\bridge\state"
) else (
  set "BRIDGE_LOG_DIR=%LOCALAPPDATA%\BYOM\bridge\logs"
  set "BRIDGE_STATE_DIR=%LOCALAPPDATA%\BYOM\bridge\state"
)
set "BRIDGE_SHARED_SECRET_PATH=%BRIDGE_STATE_DIR%\shared-secret.txt"
if not "%BYOM_BRIDGE_SHARED_SECRET_PATH%"=="" set "BRIDGE_SHARED_SECRET_PATH=%BYOM_BRIDGE_SHARED_SECRET_PATH%"
if "%BYOM_BRIDGE_SHARED_SECRET%"=="" (
  if exist "%BRIDGE_SHARED_SECRET_PATH%" (
    set /p "BYOM_BRIDGE_SHARED_SECRET="<"%BRIDGE_SHARED_SECRET_PATH%"
  )
)
if not exist "%BRIDGE_LOG_DIR%" (
  mkdir "%BRIDGE_LOG_DIR%" >nul 2>&1
)
if not exist "%BRIDGE_STATE_DIR%" (
  mkdir "%BRIDGE_STATE_DIR%" >nul 2>&1
)
set "BRIDGE_PAIRING_CODE_LOG_PATH=%BRIDGE_LOG_DIR%\pairing-code.log"
set "BRIDGE_PAIRING_STATE_PATH=%BRIDGE_STATE_DIR%\pairing-state.json"
set "BRIDGE_HANDSHAKE_STATE_PATH=%BRIDGE_STATE_DIR%\handshake-state.json"
set "BRIDGE_SESSION_KEY_STATE_PATH=%BRIDGE_STATE_DIR%\session-key-state.json"
set "BRIDGE_CLOUD_CONNECTION_STATE_PATH=%BRIDGE_STATE_DIR%\cloud-connection-state.json"
set "BYOM_BRIDGE_PAIRING_CODE_LOG_PATH=%BRIDGE_PAIRING_CODE_LOG_PATH%"
set "BYOM_BRIDGE_PAIRING_CODE_HINT=%BYOM_BRIDGE_PAIRING_CODE_LOG_PATH%"
set "BYOM_BRIDGE_PAIRING_STATE_PATH=%BRIDGE_PAIRING_STATE_PATH%"
set "BYOM_BRIDGE_HANDSHAKE_STATE_PATH=%BRIDGE_HANDSHAKE_STATE_PATH%"
set "BYOM_BRIDGE_SESSION_KEY_STATE_PATH=%BRIDGE_SESSION_KEY_STATE_PATH%"
set "BYOM_BRIDGE_CLOUD_CONNECTION_STATE_PATH=%BRIDGE_CLOUD_CONNECTION_STATE_PATH%"
if "%BYOM_BRIDGE_PREFER_WORKSPACE_ADAPTER_SOURCE%"=="" set "BYOM_BRIDGE_PREFER_WORKSPACE_ADAPTER_SOURCE=true"
if "%BYOM_CLOUD_BROKER_V2_ENABLED%"=="" set "BYOM_CLOUD_BROKER_V2_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_ANTHROPIC_API_KEY_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_ANTHROPIC_API_KEY_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_ANTHROPIC_OAUTH_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_ANTHROPIC_OAUTH_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_FOUNDRY_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_FOUNDRY_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_VERTEX_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_VERTEX_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_BEDROCK_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_BEDROCK_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_OPENAI_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_OPENAI_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_PERPLEXITY_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_PERPLEXITY_ENABLED=true"
if "%BYOM_CLOUD_PROVIDER_GEMINI_ENABLED%"=="" set "BYOM_CLOUD_PROVIDER_GEMINI_ENABLED=true"

pushd "%REPO_ROOT%"
node --loader "./scripts/dev/ts-js-specifier-loader.mjs" "./apps/bridge/src/main.ts"
set "EXIT_CODE=%ERRORLEVEL%"
popd

exit /b %EXIT_CODE%
