import { normalizeReasonCode, type ProtocolReasonCode } from "@byom-ai/protocol";

export const POLICY_DECISION_MACHINE_CODES = {
  ALLOW: "BYOM_POLICY_ALLOW",
  DENY_POLICY_MISSING: "BYOM_POLICY_DENY_POLICY_MISSING",
  DENY_POLICY_INVALID: "BYOM_POLICY_DENY_POLICY_INVALID",
  DENY_POLICY_EXPIRED: "BYOM_POLICY_DENY_POLICY_EXPIRED",
  DENY_POLICY_NO_ALLOW_RULES: "BYOM_POLICY_DENY_POLICY_NO_ALLOW_RULES",
  DENY_SIGNATURE_INVALID: "BYOM_POLICY_DENY_SIGNATURE_INVALID",
  DENY_KEY_UNAVAILABLE: "BYOM_POLICY_DENY_KEY_UNAVAILABLE",
  DENY_ORIGIN_DENIED: "BYOM_POLICY_DENY_ORIGIN_DENIED",
  DENY_ORIGIN_NOT_ALLOWED: "BYOM_POLICY_DENY_ORIGIN_NOT_ALLOWED",
  DENY_CAPABILITY_DENIED: "BYOM_POLICY_DENY_CAPABILITY_DENIED",
  DENY_CAPABILITY_NOT_ALLOWED: "BYOM_POLICY_DENY_CAPABILITY_NOT_ALLOWED",
  DENY_PROVIDER_DENIED: "BYOM_POLICY_DENY_PROVIDER_DENIED",
  DENY_PROVIDER_NOT_ALLOWED: "BYOM_POLICY_DENY_PROVIDER_NOT_ALLOWED",
  DENY_MODEL_DENIED: "BYOM_POLICY_DENY_MODEL_DENIED",
  DENY_MODEL_NOT_ALLOWED: "BYOM_POLICY_DENY_MODEL_NOT_ALLOWED",
  DENY_EVALUATION_INPUT_INVALID: "BYOM_POLICY_DENY_EVALUATION_INPUT_INVALID",
} as const;

export type PolicyDecisionMachineCode =
  (typeof POLICY_DECISION_MACHINE_CODES)[keyof typeof POLICY_DECISION_MACHINE_CODES];

export const POLICY_REASON_CODE_BY_MACHINE_CODE: Readonly<
  Record<PolicyDecisionMachineCode, ProtocolReasonCode>
> = Object.freeze({
  [POLICY_DECISION_MACHINE_CODES.ALLOW]: "allow",
  [POLICY_DECISION_MACHINE_CODES.DENY_POLICY_MISSING]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_POLICY_INVALID]: "request.invalid",
  [POLICY_DECISION_MACHINE_CODES.DENY_POLICY_EXPIRED]: "request.expired",
  [POLICY_DECISION_MACHINE_CODES.DENY_POLICY_NO_ALLOW_RULES]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_SIGNATURE_INVALID]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_KEY_UNAVAILABLE]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_ORIGIN_DENIED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_ORIGIN_NOT_ALLOWED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_CAPABILITY_DENIED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_CAPABILITY_NOT_ALLOWED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_PROVIDER_DENIED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_PROVIDER_NOT_ALLOWED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_MODEL_DENIED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_MODEL_NOT_ALLOWED]: "policy.denied",
  [POLICY_DECISION_MACHINE_CODES.DENY_EVALUATION_INPUT_INVALID]: "request.invalid",
});

const POLICY_MACHINE_CODE_SET: ReadonlySet<string> = new Set(
  Object.values(POLICY_DECISION_MACHINE_CODES),
);

export function isPolicyDecisionMachineCode(value: string): value is PolicyDecisionMachineCode {
  return POLICY_MACHINE_CODE_SET.has(value);
}

export function toPolicyReasonCode(machineCode: PolicyDecisionMachineCode): ProtocolReasonCode {
  return POLICY_REASON_CODE_BY_MACHINE_CODE[machineCode];
}

export function normalizePolicyReasonCode(input: unknown): ProtocolReasonCode {
  return normalizeReasonCode(input);
}